def checkForBingoDrop(fullStringNoDate: str, content_dict: dict):
    """
        Determine the appropriate webhook url, message, and
        MessageCategory from an in-game message

        Example of an in-game message:
            <:TaskMastericon:1147705076677345322>
            ScytheMane has completed the Hard Kandarin diary\.

        Parameters
        ----------
        fullStringNoDate: str
            Runescape message without the preceding emoji

        Returns
        -------
        dict
            The webhook url, message, and MessageCategory as a dictionary
    """
    if content_dict:
        content_dict["isBingo"] = False  # default value

        bingo_drops = [
            "Dragon pickaxe",

            # all pets
            "Abyssal orphan",
            "Baby mole",
            "Baron",
            "Bran",
            "Butch",
            "Callisto cub",
            "Dom",
            "Gull",
            "Hellpuppy",
            "Huberte",
            "Ikkle hydra",
            "Jal-nib-rek",
            "Kalphite princess",
            "Lil' zik",
            "Lil'viathan",
            "Little nightmare",
            "Moxi",
            "Muphin",
            "Nexling",
            "Nid",
            "Noon",
            "Olmlet",
            "Pet chaos elemental",
            "Pet dagannoth prime",
            "Pet dagannoth rex",
            "Pet dagannoth supreme",
            "Pet dark core",
            "Pet general graardor",
            "Pet k'ril tsutsaroth",
            "Pet kraken",
            "Pet kree'arra",
            "Pet smoke devil",
            "Pet snakeling",
            "Pet zilyana",
            "Phoenix",
            "Prince black dragon",
            "Scorpia's offspring",
            "Scurry",
            "Skotos",
            "Smolcano",
            "Smol heredit",
            "Sraracha",
            "Tiny tempor",
            "Tumeken's guardian",
            "Tzrek-jad",
            "Venenatis spiderling",
            "Vet'ion jr.",
            "Vorki",
            "Wisp",
            "Yami",
            "Youngllef",
            "Baby chinchompa",
            "Beaver",
            "Giant squirrel",
            "Heron",
            "Rift guardian",
            "Rock golem",
            "Rocky",
            "Tangleroot",
            "Abyssal protector",
            "Bloodhound",
            "Chompy chick",
            "Herbi",
            "Lil' creator",
            "Pet penance queen",
            "Quetzin",
            # 3 Gauntlet Uniques
            "Crystal weapon seed",
            "Crystal armour seed",
            "Enhanced crystal weapon seed",
            # Dragon Warhammer
            "Dragon warhammer",
            # TDS Uniques (Tormented Demons)
            "Tormented synapse",
            "Burning claw",
            # Any Raids Weapon - CoX
            "Twisted bow",
            "Elder maul",
            "Kodai insignia",
            "Dragon claws",
            "Dragon hunter crossbow",
            "Dinh's bulwark",
            # Any Raids Weapon - ToB
            "Scythe of vitur",
            "Ghrazi rapier",
            "Sanguinesti staff",
            # Any Raids Weapon - ToA
            "Tumeken's shadow",
            "Osmumten's fang",
            # Blowpipe
            "Tanzanite fang",
            # Any Muspah Unique
            "Venator shard",
            "Ancient icon",
            # Any GOTR Dye
            "Abyssal red dye",
            "Abyssal green dye",
            "Abyssal blue dye",
            # Any Godwars Hilt
            "Armadyl hilt",
            "Bandos hilt",
            "Saradomin hilt",
            "Zamorak hilt",
            "Ancient hilt",
            # Big Fish (Any)
            "Big bass",
            "Big shark",
            "Big swordfish",
            "Big harpoonfish",
            "Giant blue krill",
            "Golden haddock",
            "Orangefin",
            "Huge halibut",
            "Purplefin",
            "Swift marlin",
            "Golden tench",
            # Enhanced Teleport seed
            "Enhanced crystal teleport seed",
            # Zalcano Unique
            "Crystal tool seed",
            "Zalcano shard",
            "Uncut onyx",
            # Salvaging unique ??? unknown - will ask clan
            "Rusty locket",
            "Mouldy block",
            "Dull knife",
            "Broken compass",
            "Rusty coin",
            "Broken sextant",
            "Smashed mirror",
            "Mouldy doll",
            "Dragon cannon barrel",
            "Soup",
            # Any Medium Clue Boot
            "Ranger boots",
            "Wizard boots",
            "Holy sandals",
            # Pharaoh's Sceptre
            "Pharaoh's sceptre",
            # Tome of Fire
            "Tome of fire",
            # Obtain a Fire cape
            "Fire cape",
            # Blood Shard
            "Blood shard",
            # 3 Moons Uniques (Moons of Peril)
            "Blood moon helm",
            "Blood moon chestplate",
            "Blood moon tassets",
            "Dual macuahuitl",
            "Blue moon helm",
            "Blue moon chestplate",
            "Blue moon tassets",
            "Blue moon spear",
            "Eclipse moon helm",
            "Eclipse moon chestplate",
            "Eclipse moon tassets",
            "Eclipse atlatl",
            # Tome of Water
            "Tome of water",
            # Demonics Unique
            "Zenyte shard",
        ]

        # bingo_drops = [
        #     "Spectral sigil",
        #     "Arcane sigil",
        #     "Elysian sigil",
        #     "Dragon warhammer",
        #     "Fighter torso",
        #     "Crystal grail",
        #     "Hydra's claw",
        #     "Scythe of vitur (uncharged)",
        #     "Dragon full helm",
        #     "Mole slippers",
        #     "Tormented synapse",
        #     "Tanzanite fang",
        #     "Primordial crystal",
        #     "Pegasian crystal",
        #     "Eternal crystal",
        #     "Jar of chemicals",
        #     "Jar of darkness",
        #     "Jar of decay",
        #     "Jar of dirt",
        #     "Jar of dreams",
        #     "Jar of eyes",
        #     "Jar of miasma",
        #     "Jar of sand",
        #     "Jar of smoke",
        #     "Jar of souls",
        #     "Jar of spirits",
        #     "Jar of stone",
        #     "Jar of swamp",
        #     "Jar of venom",
        #     "Tumeken's shadow (uncharged)",
        #     "Masori mask",
        #     "Masori body",
        #     "Masori chaps",
        #     "Blood shard",
        #     "Crystal armour seed",
        #     "Enhanced crystal weapon seed",
        #     "Felling axe handle",
        #     "Bottomless compost bucket",
        #     "Twisted bow",
        #     "Ancestral hat",
        #     "Ancestral robe top",
        #     "Ancestral robe bottom",
        #     "Gilded spade",
        #     "Gilded axe",
        #     "Gilded pickaxe",
        #     "Gilded hasta",
        #     "Gilded spear",
        #     "Gilded scimitar",
        #     "Gilded 2h sword",
        #     "Gilded full helm",
        #     "Gilded med helm",
        #     "Gilded platebody",
        #     "Gilded chainbody",
        #     "Gilded platelegs",
        #     "Gilded plateskirt",
        #     "Gilded kiteshield",
        #     "Gilded sq shield",
        #     "Gilded boots",
        #     "Gilded coif",
        #     "Gilded d'hide body",
        #     "Gilded d'hide chaps",
        #     "Gilded d'hide vambraces",
        #     "Basilisk jaw",
        #     "Amulet of eternal glory",
        #     "Fletching knife",
        #     "Obsidian platebody",
        #     "Obsidian platelegs",
        #     "Elder chaos hood",
        #     "Elder chaos top",
        #     "Elder chaos robe",
        #     "Evil chicken head",
        #     "Evil chicken wings",
        #     "Evil chicken legs",
        #     "Evil chicken feet",
        #     "Zamorakian spear",
        #     "Pirate's hook",
        #     "Dragon pickaxe",
        #     "Craw's bow (u)",
        #     "Thammaron's sceptre (u)",
        #     "Viggora's chainmace (u)",
        #     "Golden tench",
        #     "champion scroll",
        #     "Justiciar faceguard",
        #     "Justiciar chestguard",
        #     "Justiciar legguards",
        #     "Mage's book",
        #     "Ballista limbs",
        #     "Ballista spring",
        #     "Heavy frame",
        #     "Monkey tail",
        #     "Ahrim's hood",
        #     "Ahrim's robetop",
        #     "Ahrim's robeskirt",
        #     "Ahrim's staff",
        #     "Dharok's helm",
        #     "Dharok's platebody",
        #     "Dharok's platelegs",
        #     "Dharok's greataxe",
        #     "Guthan's helm",
        #     "Guthan's platebody",
        #     "Guthan's chainskirt",
        #     "Guthan's warspear",
        #     "Karil's coif",
        #     "Karil's leathertop",
        #     "Karil's leatherskirt",
        #     "Karil's crossbow",
        #     "Torag's helm",
        #     "Torag's platebody",
        #     "Torag's platelegs",
        #     "Torag's hammers",
        #     "Verac's helm",
        #     "Verac's brassard",
        #     "Verac's plateskirt",
        #     "Verac's flail",
        #     "Zenyte shard",
        #     "Dagon'hai hat",
        #     "Dagon'hai robe top",
        #     "Dagon'hai robe bottom",
        #     "Abyssal whip",
        #     "vestige",
        #     "dragon mask",
        #     "Magic fang",
        #     "Abyssal lantern",
        #     "Abyssal needle",
        #     "Dragon chainbody",
        #     "Sarachnis cudgel",
        #     "Voidwaker blade",
        #     "Voidwaker hilt",
        #     "Voidwaker gem",
        #     "Sunfire fanatic helm",
        #     "Sunfire fanatic cuirass",
        #     "Sunfire fanatic chausses",
        #     "Tonalztics of ralos (uncharged)",
        #     "Uncut onyx",
        #     "Venator shard",
        #     "Ice element staff crown",
        #     "Fire element staff crown",
        #     "Odium shard",
        #     "Odium shard",
        #     "Odium shard",
        #     "Berserker ring",
        #     "Archers ring",
        #     "Seers ring",
        #     "Team cape zero",
        #     "Team cape i",
        #     "Team cape x",
        #     "Cape of skulls",
        #     "Seed box",
        #     "Virtus mask",
        #     "Virtus robe top",
        #     "Virtus robe bottom",
        #     "Oathplate helm",
        #     "Oathplate chest",
        #     "Oathplate legs",
        #     "Ham joint",
        #     "Draconic visage",
        #     "Araxyte fang",
        #     "Imbued heart",
        #     "Pet snakeling",
        #     "Mask of ranul",
        #     "Antler guard",
        #     "Eternal gem",
        #     "Ancient hilt",
        #     "Armadyl hilt",
        #     "Bandos hilt",
        #     "Saradomin hilt",
        #     "Zamorak hilt",
        #     "Abyssal dagger",
        #     "Occult necklace",
        #     "Brine sabre",
        #     "Fish barrel",
        #     "Tackle box",
        #     "Big harpoonfish",
        #     "Tome of water (empty)",
        #     "Dragon harpoon",
        #     "Big shark",
        #     "Avernic treads",
        #     "Eye of ayak (uncharged)",
        #     "Mokhaiotl cloth",
        #     "Dom",
        #     "Scurry",
        #     "Nightmare staff",
        #     "Inquisitor's great helm",
        #     "Inquisitor's hauberk",
        #     "Inquisitor's plateskirt",
        #     "Inquisitor's mace",
        #     "Eldritch orb",
        #     "Harmonised orb",
        #     "Volatile orb",
        #     "Parasitic egg",
        #     "Little nightmare",
        #     "Slepey tablet",
        #     "Beaver",
        #     "Rock golem",
        #     "Lil' zik",
        #     "Nid",
        #     "Sraracha",
        #     "Venenatis spiderling",
        #     "Rocky",
        #     "Heron",
        #     "Zaryte vambraces",
        #     "Nihil horn",
        #     "Torva full helm (damaged)",
        #     "Torva platebody (damaged)",
        #     "Torva platelegs (damaged)",
        #     "Ancient hilt",
        #     "Nexling",
        #     "Pet dagannoth rex",
        #     "Tangleroot",
        #     "Hellpuppy",
        #     "Chompy chick",
        #     "Callisto cub",
        #     "Vet'ion jr",
        #     "Pet chaos elemental",
        #     "Pet kree'arra",
        #     "Pet zilyana",
        #     "Pet k'ril tsutsaroth",
        #     "Pet general graardor",
        #     "Tiny tempor"
        # ]
        
        team_red = [
            "UncleSerb",
            "0SONOVABISH0",
            "BirnDream",
            "Bring now",
            "Bus 2 Lumby",
            "Cananana",
            "Dairy Base",
            "Dundiez",
            "Gaspii",
            "Haaters",
            "OldThcool",
            "ROLlTO",
            "Spahrten",
            "Stale Prince",
            "Uber2Lumb",
            "W 0 W S"
        ]

        team_blue = [
            "Out of Dabb",
            "505",
            "canabisaurus",
            "Dharmz66",
            "FL0WSTATE",
            "Gartographer",
            "Kick My_Kill",
            "Listus",
            "nayboor",
            "NIEVES STRAP",
            "PizzacatNL",
            "t00l shed",
            "tw1sted pyro",
            "wawb",
            "Wont Take Me",
            "Nokowt"
        ]


        # Determine if drop is bingo-related
        for drop in bingo_drops:
            if drop in fullStringNoDate:
                content_dict["isBingo"] = True
                break
        
        # Now determine team - green, blue, red
        if content_dict["isBingo"]:
            for name in team_blue:
                if name in fullStringNoDate:
                    # send to blue team drop webhook
                    content_dict["teamName"] = "blue"
                    return content_dict

            for name in team_red:
                if name in fullStringNoDate:
                    # send to red team drop webhook
                    content_dict["teamName"] = "red"
                    return content_dict

    return content_dict
