services:
  rock-discord-db:
    image: postgres:16.3
    container_name: rock-discord-db-container
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - rock-discord-bot-data:/var/lib/postgresql/data

volumes:
  rock-discord-bot-data:
